### ISSUE TITLE
Får feilmelding 'contactTeacher' of undefined

### ISSUE THREAD

**Issue by maccyber** [telemark/buddy-minelev-api#2]
2016-02-08T14:58:50.743310717Z     TypeError: Uncaught error: Cannot read property 'contactTeacher' of undefined
D2016-02-08T14:58:50.743325337Z     at /src/handlers/index.js:245:60
R2016-02-08T14:58:50.743336834Z     at /src/node_modules/wreck/lib/index.js:473:20
[2016-02-08T14:58:50.743346902Z     at finish (/src/node_modules/wreck/lib/index.js:319:16)
[2016-02-08T14:58:50.743357071Z     at wrapped (/src/node_modules/hoek/lib/index.js:867:20)
c2016-02-08T14:58:50.743367389Z     at onReaderFinish (/src/node_modules/wreck/lib/index.js:365:16)
;2016-02-08T14:58:50.743377271Z     at g (events.js:260:16)
A2016-02-08T14:58:50.743386328Z     at emitNone (events.js:72:20)
=2016-02-08T14:58:50.743395492Z     at emit (events.js:166:7)
O2016-02-08T14:58:50.743404986Z     at finishMaybe (_stream_writable.js:468:14)
M2016-02-08T14:58:50.743414698Z     at afterWrite (_stream_writable.js:347:3)

**Comment by maccyber** [comment]
Lurer på om denne kom pga "Token expired"

**Comment by zrrrzzt** [comment]
jeg skulle til å foreslå det samme. great minds osv

Dette er fikset i siste push, men om du vil teste er det bare å søke frem elev og vente 60 min med å trykke knapp for å skrive varsel

**Comment by maccyber** [comment]
Everything on it's right place
Ser ut til at jeg blir utlogget når session dør nå.
