### ISSUE TITLE
Hente userids for alle mine studenter

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/buddy-minelev-api#5]
```/users/{username}/studentids```=> array med ids

**Comment by maccyber** [comment]
Mulig også /users/{username}/groupids

**Comment by zrrrzzt** [comment]
Man kan sette opp textindex i MongoDB og søke via den, men det blir ikke riktig å ta det denne veien.
Formålet er å finne alle man er kontaktlærer for, også de man ikke underviser i gitte fag

**Comment by maccyber** [comment]
Ser ikke hva som blir feil med
* Hent fra logg [grupper jeg har tilknytning til]

I forhold til

* Hent fra logg [studenter jeg har tilknytning til]

Annet enn at det er litt mongo å søke med textindex

**Comment by zrrrzzt** [comment]
Dersom du har elever via klassegrupper og ikke undervisningsgrupper blir det vel ikke rett?
Men, jeg har ikke modellen i hodet altså
